version: '3.7'
services:
  app:
    build:
      args:
        user: webuser
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: ap-laravel
    container_name: ap-app
    restart: unless-stopped
    logging:
      options:
        max-size: "5k"
    ports:
      - '5173:5173'
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./dev/docker-compose/php/app.ini:/usr/local/etc/php/conf.d/app.ini
    extra_hosts:
      # docker inspect ap-app | grep Gateway
      - host.docker.internal:host-gateway
    networks:
      - ap

  nginx:
    image: nginx:alpine
    container_name: ap-nginx
    restart: unless-stopped
    logging:
      options:
        max-size: "5k"
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www
      - ./dev/docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - ap

  database:
      image: postgres:13
      container_name: ap-postgres
      restart: always
      environment:
          POSTGRES_DB: laravel
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secret
      ports:
          - "5432:5432"
      volumes:
          - db_postgres:/var/lib/postgresql/data
      networks:
          - ap
volumes:
    db_postgres:

networks:
  ap:
    driver: bridge
