version: '3.8'
services:
  database:
    image: postgres:13
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
  
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: .
      dockerfile: Dockerfile
    image: lennon/php-laravel
    container_name: app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network
    depends_on:
      - database

  nginx:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/:/etc/nginx/conf.d/
    networks:
      - app-network



volumes:
  db_data:

networks:
  app-network:
    driver: bridge